cd ~/.madp/results/GMAA/
rm -r ACC-error-s0
rm -r ACC-standby-s0
rm -r ACC-following-s0
rm -r ACC-speedcontrol-s0
rm -r ACC-hold-s0
rm -r ACC-override-s0
rm -r ACC-error-s1
rm -r ACC-standby-s1
rm -r ACC-following-s1
rm -r ACC-speedcontrol-s1
rm -r ACC-hold-s1
rm -r ACC-override-s1
rm -r ACC-error-s2
rm -r ACC-standby-s2
rm -r ACC-following-s2
rm -r ACC-speedcontrol-s2
rm -r ACC-hold-s2
rm -r ACC-override-s2
rm -r ACC-error-s3
rm -r ACC-standby-s3
rm -r ACC-following-s3
rm -r ACC-speedcontrol-s3
rm -r ACC-hold-s3
rm -r ACC-override-s3
rm -r ACC-error-s4
rm -r ACC-standby-s4
rm -r ACC-following-s4
rm -r ACC-speedcontrol-s4
rm -r ACC-hold-s4
rm -r ACC-override-s4
rm -r ACC-error-s5
rm -r ACC-standby-s5
rm -r ACC-following-s5
rm -r ACC-speedcontrol-s5
rm -r ACC-hold-s5
rm -r ACC-override-s5
rm -r ACC-error-s6
rm -r ACC-standby-s6
rm -r ACC-following-s6
rm -r ACC-speedcontrol-s6
rm -r ACC-hold-s6
rm -r ACC-override-s6
rm -r ACC-error-s7
rm -r ACC-standby-s7
rm -r ACC-following-s7
rm -r ACC-speedcontrol-s7
rm -r ACC-hold-s7
rm -r ACC-override-s7
rm optimalValueDatabase