cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-AM_AM_restarts10_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-MP_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QBG_QAVMonahanBG_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QPOMDP_QAVMonahanPOMDP_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-AM_AM_restarts10_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-MP_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QBG_QAVMonahanBG_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QPOMDP_QAVMonahanPOMDP_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-AM_AM_restarts10_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-MP_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QBG_QAVMonahanBG_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QPOMDP_QAVMonahanPOMDP_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-AM_AM_restarts10_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-MP_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QBG_QAVMonahanBG_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QPOMDP_QAVMonahanPOMDP_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-AM_AM_restarts10_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-MP_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QBG_QAVMonahanBG_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QPOMDP_QAVMonahanPOMDP_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-AM_AM_restarts10_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-MP_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QBG_QAVMonahanBG_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QPOMDP_QAVMonahanPOMDP_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-AM_AM_restarts10_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-MP_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QBG_QAVMonahanBG_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QPOMDP_QAVMonahanPOMDP_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-AM_AM_restarts10_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-MP_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QBG_QAVMonahanBG_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QPOMDP_QAVMonahanPOMDP_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QAVMonahanBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QAVMonahanPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QAVQBGPlanner_TreeIncPruneBnB_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QAVTreeIncPruneU1CS1VC1BG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QHybrid_QBG_QAVMonahanBG_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QHybrid_QPOMDP_QAVMonahanPOMDP_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-AM_AM_restarts10_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QMDP_h2_restarts1_NoCache_BGIP-MP_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_FSPC_QPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QAVMonahanBG_h2_restarts1_k1000_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QAVMonahanPOMDP_h2_restarts1_k1000_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QBG_h2_restarts1_k1000_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QHybrid_QPOMDP_QAVMonahanPOMDP_hLT0_h2_restarts1_k1000_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1000_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-BnB_ka0_JTOIdentityMapping_CCI1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QMDP_h2_restarts1_k1_NoCache_BGIP-CE_CEr10_i50_s50_sfu10_a0.3_ht1_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_kGMAA_QPOMDP_h2_restarts1_k1000_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVMonahanPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVQBGPlanner_TreeIncPruneBnB_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QAVTreeIncPruneU1CS1VC1BG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QBG_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QBG_QAVMonahanBG_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QHybrid_QPOMDP_QAVMonahanPOMDP_hLT0_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
cat ~/.madp/results/GMAA/ACC-ss-standby-scen-1/GMAA_ACC-ss-standby-scen-1_MAAstar_QPOMDP_h2_restarts1_NoCache_BGIP-BFS_JPol
