sh InitializeResultFiles.sh
python3 GetResults.py ACC-nocomm-standby-s0 standby 0 ACC-nocomm
python3 GetResults.py ACC-nocomm-following-s0 following 0 ACC-nocomm
python3 GetResults.py ACC-nocomm-speedcontrol-s0 speedcontrol 0 ACC-nocomm
python3 GetResults.py ACC-nocomm-error-s0 error 0 ACC-nocomm
python3 GetResults.py ACC-nocomm-hold-s0 hold 0 ACC-nocomm
python3 GetResults.py ACC-nocomm-override-s0 override 0 ACC-nocomm
python3 GetResults.py ACC-nocomm-standby-s1 standby 1 ACC-nocomm
python3 GetResults.py ACC-nocomm-following-s1 following 1 ACC-nocomm
python3 GetResults.py ACC-nocomm-speedcontrol-s1 speedcontrol 1 ACC-nocomm
python3 GetResults.py ACC-nocomm-error-s1 error 1 ACC-nocomm
python3 GetResults.py ACC-nocomm-hold-s1 hold 1 ACC-nocomm
python3 GetResults.py ACC-nocomm-override-s1 override 1 ACC-nocomm
python3 GetResults.py ACC-nocomm-standby-s2 standby 2 ACC-nocomm
python3 GetResults.py ACC-nocomm-following-s2 following 2 ACC-nocomm
python3 GetResults.py ACC-nocomm-speedcontrol-s2 speedcontrol 2 ACC-nocomm
python3 GetResults.py ACC-nocomm-error-s2 error 2 ACC-nocomm
python3 GetResults.py ACC-nocomm-hold-s2 hold 2 ACC-nocomm
python3 GetResults.py ACC-nocomm-override-s2 override 2 ACC-nocomm
python3 GetResults.py ACC-nocomm-standby-s3 standby 3 ACC-nocomm
python3 GetResults.py ACC-nocomm-following-s3 following 3 ACC-nocomm
python3 GetResults.py ACC-nocomm-speedcontrol-s3 speedcontrol 3 ACC-nocomm
python3 GetResults.py ACC-nocomm-error-s3 error 3 ACC-nocomm
python3 GetResults.py ACC-nocomm-hold-s3 hold 3 ACC-nocomm
python3 GetResults.py ACC-nocomm-override-s3 override 3 ACC-nocomm
python3 GetResults.py ACC-nocomm-standby-s4 standby 4 ACC-nocomm
python3 GetResults.py ACC-nocomm-following-s4 following 4 ACC-nocomm
python3 GetResults.py ACC-nocomm-speedcontrol-s4 speedcontrol 4 ACC-nocomm
python3 GetResults.py ACC-nocomm-error-s4 error 4 ACC-nocomm
python3 GetResults.py ACC-nocomm-hold-s4 hold 4 ACC-nocomm
python3 GetResults.py ACC-nocomm-override-s4 override 4 ACC-nocomm
python3 GetResults.py ACC-nocomm-standby-s5 standby 5 ACC-nocomm
python3 GetResults.py ACC-nocomm-following-s5 following 5 ACC-nocomm
python3 GetResults.py ACC-nocomm-speedcontrol-s5 speedcontrol 5 ACC-nocomm
python3 GetResults.py ACC-nocomm-error-s5 error 5 ACC-nocomm
python3 GetResults.py ACC-nocomm-hold-s5 hold 5 ACC-nocomm
python3 GetResults.py ACC-nocomm-override-s5 override 5 ACC-nocomm
python3 GetResults.py ACC-nocomm-standby-s6 standby 6 ACC-nocomm
python3 GetResults.py ACC-nocomm-following-s6 following 6 ACC-nocomm
python3 GetResults.py ACC-nocomm-speedcontrol-s6 speedcontrol 6 ACC-nocomm
python3 GetResults.py ACC-nocomm-error-s6 error 6 ACC-nocomm
python3 GetResults.py ACC-nocomm-hold-s6 hold 6 ACC-nocomm
python3 GetResults.py ACC-nocomm-override-s6 override 6 ACC-nocomm
python3 GetResults.py ACC-nocomm-standby-s7 standby 7 ACC-nocomm
python3 GetResults.py ACC-nocomm-following-s7 following 7 ACC-nocomm
python3 GetResults.py ACC-nocomm-speedcontrol-s7 speedcontrol 7 ACC-nocomm
python3 GetResults.py ACC-nocomm-error-s7 error 7 ACC-nocomm
python3 GetResults.py ACC-nocomm-hold-s7 hold 7 ACC-nocomm
python3 GetResults.py ACC-nocomm-override-s7 override 7 ACC-nocomm
