~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-standby-scen-1.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-following-scen-1.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-speedcontrol-scen-1.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-hold-scen-1.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-override-scen-1.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-error-scen-1.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-standby-scen-2.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-following-scen-2.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-speedcontrol-scen-2.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-hold-scen-2.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-override-scen-2.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-error-scen-2.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-standby-scen-3.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-following-scen-3.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-speedcontrol-scen-3.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-hold-scen-3.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-override-scen-3.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-error-scen-3.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-standby-scen-4.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-following-scen-4.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-speedcontrol-scen-4.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-hold-scen-4.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-override-scen-4.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-error-scen-4.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-standby-scen-5.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-following-scen-5.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-speedcontrol-scen-5.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-hold-scen-5.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-override-scen-5.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-error-scen-5.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-standby-scen-6.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-following-scen-6.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-speedcontrol-scen-6.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-hold-scen-6.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-override-scen-6.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-error-scen-6.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-standby-scen-7.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-following-scen-7.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-speedcontrol-scen-7.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-hold-scen-7.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-override-scen-7.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-error-scen-7.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-standby-scen-8.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-following-scen-8.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-speedcontrol-scen-8.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-hold-scen-8.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-override-scen-8.dpomdp -h2
~/public/alyssadecpomdp/MADP/src/solvers/GMAA --GMAA=kGMAA --BGIP_Solver=AM MADPtools/ACC/ACC-ss-error-scen-8.dpomdp -h2
