python3 GetResults.py ACCmin-standby-s0 standby 0 ACCmin
python3 GetResults.py ACCmin-following-s0 following 0 ACCmin
python3 GetResults.py ACCmin-speedcontrol-s0 speedcontrol 0 ACCmin
python3 GetResults.py ACCmin-error-s0 error 0 ACCmin
python3 GetResults.py ACCmin-hold-s0 hold 0 ACCmin
python3 GetResults.py ACCmin-standby-s1 standby 1 ACCmin
python3 GetResults.py ACCmin-following-s1 following 1 ACCmin
python3 GetResults.py ACCmin-speedcontrol-s1 speedcontrol 1 ACCmin
python3 GetResults.py ACCmin-error-s1 error 1 ACCmin
python3 GetResults.py ACCmin-hold-s1 hold 1 ACCmin
python3 GetResults.py ACCmin-standby-s2 standby 2 ACCmin
python3 GetResults.py ACCmin-following-s2 following 2 ACCmin
python3 GetResults.py ACCmin-speedcontrol-s2 speedcontrol 2 ACCmin
python3 GetResults.py ACCmin-error-s2 error 2 ACCmin
python3 GetResults.py ACCmin-hold-s2 hold 2 ACCmin
python3 GetResults.py ACCmin-standby-s3 standby 3 ACCmin
python3 GetResults.py ACCmin-following-s3 following 3 ACCmin
python3 GetResults.py ACCmin-speedcontrol-s3 speedcontrol 3 ACCmin
python3 GetResults.py ACCmin-error-s3 error 3 ACCmin
python3 GetResults.py ACCmin-hold-s3 hold 3 ACCmin
python3 GetResults.py ACCmin-standby-s4 standby 4 ACCmin
python3 GetResults.py ACCmin-following-s4 following 4 ACCmin
python3 GetResults.py ACCmin-speedcontrol-s4 speedcontrol 4 ACCmin
python3 GetResults.py ACCmin-error-s4 error 4 ACCmin
python3 GetResults.py ACCmin-hold-s4 hold 4 ACCmin
python3 GetResults.py ACCmin-standby-s5 standby 5 ACCmin
python3 GetResults.py ACCmin-following-s5 following 5 ACCmin
python3 GetResults.py ACCmin-speedcontrol-s5 speedcontrol 5 ACCmin
python3 GetResults.py ACCmin-error-s5 error 5 ACCmin
python3 GetResults.py ACCmin-hold-s5 hold 5 ACCmin
python3 GetResults.py ACCmin-standby-s6 standby 6 ACCmin
python3 GetResults.py ACCmin-following-s6 following 6 ACCmin
python3 GetResults.py ACCmin-speedcontrol-s6 speedcontrol 6 ACCmin
python3 GetResults.py ACCmin-error-s6 error 6 ACCmin
python3 GetResults.py ACCmin-hold-s6 hold 6 ACCmin
python3 GetResults.py ACCmin-standby-s7 standby 7 ACCmin
python3 GetResults.py ACCmin-following-s7 following 7 ACCmin
python3 GetResults.py ACCmin-speedcontrol-s7 speedcontrol 7 ACCmin
python3 GetResults.py ACCmin-error-s7 error 7 ACCmin
python3 GetResults.py ACCmin-hold-s7 hold 7 ACCmin
