timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BFS -Q QMDP ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BFS -Q QPOMDP ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BFS -Q QBG ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BFS -Q QMDPc ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BFS -Q QPOMDPav ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BFS -Q QBGav ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BFS -Q QHybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BFS -Q QPOMDPhybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BFS -Q QBGhybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BFS -Q QBGTreeIncPrune ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BFS -Q QBGTreeIncPruneBnB ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B AM -Q QMDP ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B AM -Q QPOMDP ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B AM -Q QBG ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B AM -Q QMDPc ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B AM -Q QPOMDPav ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B AM -Q QBGav ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B AM -Q QHybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B AM -Q QPOMDPhybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B AM -Q QBGhybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B AM -Q QBGTreeIncPrune ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B AM -Q QBGTreeIncPruneBnB ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B CE -Q QMDP ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B CE -Q QPOMDP ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B CE -Q QBG ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B CE -Q QMDPc ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B CE -Q QPOMDPav ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B CE -Q QBGav ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B CE -Q QHybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B CE -Q QPOMDPhybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B CE -Q QBGhybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B CE -Q QBGTreeIncPrune ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B CE -Q QBGTreeIncPruneBnB ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B MP -Q QMDP ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B MP -Q QPOMDP ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B MP -Q QBG ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B MP -Q QMDPc ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B MP -Q QPOMDPav ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B MP -Q QBGav ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B MP -Q QHybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B MP -Q QPOMDPhybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B MP -Q QBGhybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B MP -Q QBGTreeIncPrune ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B MP -Q QBGTreeIncPruneBnB ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BnB -Q QMDP ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BnB -Q QPOMDP ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BnB -Q QBG ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BnB -Q QMDPc ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BnB -Q QPOMDPav ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BnB -Q QBGav ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BnB -Q QHybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BnB -Q QPOMDPhybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BnB -Q QBGhybrid ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BnB -Q QBGTreeIncPrune ACC/ACC-ss-standby-scen-1.dpomdp -h2
timeout -k 5m 5m ../MADP/src/solvers/GMAA -G MAAstar -B BnB -Q QBGTreeIncPruneBnB ACC/ACC-ss-standby-scen-1.dpomdp -h2
