python3 GetResults.py ACC-standby-s1 standby 1
python3 GetResults.py ACC-following-s1 following 1
python3 GetResults.py ACC-speedcontrol-s1 speedcontrol 1
python3 GetResults.py ACC-error-s1 error 1
python3 GetResults.py ACC-hold-s1 hold 1
python3 GetResults.py ACC-override-s1 override 1
python3 GetResults.py ACC-standby-s2 standby 2
python3 GetResults.py ACC-following-s2 following 2
python3 GetResults.py ACC-speedcontrol-s2 speedcontrol 2
python3 GetResults.py ACC-error-s2 error 2
python3 GetResults.py ACC-hold-s2 hold 2
python3 GetResults.py ACC-override-s2 override 2
python3 GetResults.py ACC-standby-s3 standby 3
python3 GetResults.py ACC-following-s3 following 3
python3 GetResults.py ACC-speedcontrol-s3 speedcontrol 3
python3 GetResults.py ACC-error-s3 error 3
python3 GetResults.py ACC-hold-s3 hold 3
python3 GetResults.py ACC-override-s3 override 3
python3 GetResults.py ACC-standby-s4 standby 4
python3 GetResults.py ACC-following-s4 following 4
python3 GetResults.py ACC-speedcontrol-s4 speedcontrol 4
python3 GetResults.py ACC-error-s4 error 4
python3 GetResults.py ACC-hold-s4 hold 4
python3 GetResults.py ACC-override-s4 override 4
python3 GetResults.py ACC-standby-s5 standby 5
python3 GetResults.py ACC-following-s5 following 5
python3 GetResults.py ACC-speedcontrol-s5 speedcontrol 5
python3 GetResults.py ACC-error-s5 error 5
python3 GetResults.py ACC-hold-s5 hold 5
python3 GetResults.py ACC-override-s5 override 5
python3 GetResults.py ACC-standby-s6 standby 6
python3 GetResults.py ACC-following-s6 following 6
python3 GetResults.py ACC-speedcontrol-s6 speedcontrol 6
python3 GetResults.py ACC-error-s6 error 6
python3 GetResults.py ACC-hold-s6 hold 6
python3 GetResults.py ACC-override-s6 override 6
python3 GetResults.py ACC-standby-s7 standby 7
python3 GetResults.py ACC-following-s7 following 7
python3 GetResults.py ACC-speedcontrol-s7 speedcontrol 7
python3 GetResults.py ACC-error-s7 error 7
python3 GetResults.py ACC-hold-s7 hold 7
python3 GetResults.py ACC-override-s7 override 7
python3 GetResults.py ACC-standby-s8 standby 8
python3 GetResults.py ACC-following-s8 following 8
python3 GetResults.py ACC-speedcontrol-s8 speedcontrol 8
python3 GetResults.py ACC-error-s8 error 8
python3 GetResults.py ACC-hold-s8 hold 8
python3 GetResults.py ACC-override-s8 override 8
