python3 GetResults.py ACC-ss-standby-scen-1 standby 1
python3 GetResults.py ACC-ss-following-scen-1 following 1
python3 GetResults.py ACC-ss-speedcontrol-scen-1 speedcontrol 1
python3 GetResults.py ACC-ss-hold-scen-1 hold 1
python3 GetResults.py ACC-ss-override-scen-1 override 1
python3 GetResults.py ACC-ss-error-scen-1 error 1
python3 GetResults.py ACC-ss-standby-scen-2 standby 2
python3 GetResults.py ACC-ss-following-scen-2 following 2
python3 GetResults.py ACC-ss-speedcontrol-scen-2 speedcontrol 2
python3 GetResults.py ACC-ss-hold-scen-2 hold 2
python3 GetResults.py ACC-ss-override-scen-2 override 2
python3 GetResults.py ACC-ss-error-scen-2 error 2
python3 GetResults.py ACC-ss-standby-scen-3 standby 3
python3 GetResults.py ACC-ss-following-scen-3 following 3
python3 GetResults.py ACC-ss-speedcontrol-scen-3 speedcontrol 3
python3 GetResults.py ACC-ss-hold-scen-3 hold 3
python3 GetResults.py ACC-ss-override-scen-3 override 3
python3 GetResults.py ACC-ss-error-scen-3 error 3
python3 GetResults.py ACC-ss-standby-scen-4 standby 4
python3 GetResults.py ACC-ss-following-scen-4 following 4
python3 GetResults.py ACC-ss-speedcontrol-scen-4 speedcontrol 4
python3 GetResults.py ACC-ss-hold-scen-4 hold 4
python3 GetResults.py ACC-ss-override-scen-4 override 4
python3 GetResults.py ACC-ss-error-scen-4 error 4
python3 GetResults.py ACC-ss-standby-scen-5 standby 5
python3 GetResults.py ACC-ss-following-scen-5 following 5
python3 GetResults.py ACC-ss-speedcontrol-scen-5 speedcontrol 5
python3 GetResults.py ACC-ss-hold-scen-5 hold 5
python3 GetResults.py ACC-ss-override-scen-5 override 5
python3 GetResults.py ACC-ss-error-scen-5 error 5
python3 GetResults.py ACC-ss-standby-scen-6 standby 6
python3 GetResults.py ACC-ss-following-scen-6 following 6
python3 GetResults.py ACC-ss-speedcontrol-scen-6 speedcontrol 6
python3 GetResults.py ACC-ss-hold-scen-6 hold 6
python3 GetResults.py ACC-ss-override-scen-6 override 6
python3 GetResults.py ACC-ss-error-scen-6 error 6
python3 GetResults.py ACC-ss-standby-scen-7 standby 7
python3 GetResults.py ACC-ss-following-scen-7 following 7
python3 GetResults.py ACC-ss-speedcontrol-scen-7 speedcontrol 7
python3 GetResults.py ACC-ss-hold-scen-7 hold 7
python3 GetResults.py ACC-ss-override-scen-7 override 7
python3 GetResults.py ACC-ss-error-scen-7 error 7
python3 GetResults.py ACC-ss-standby-scen-8 standby 8
python3 GetResults.py ACC-ss-following-scen-8 following 8
python3 GetResults.py ACC-ss-speedcontrol-scen-8 speedcontrol 8
python3 GetResults.py ACC-ss-hold-scen-8 hold 8
python3 GetResults.py ACC-ss-override-scen-8 override 8
python3 GetResults.py ACC-ss-error-scen-8 error 8
