sh InitializeResultFiles.sh
cd ..
cd MADPtools
python3 GetResults.py ACC-standby-s0 standby 0 ACC
python3 GetResults.py ACC-following-s0 following 0 ACC
python3 GetResults.py ACC-speedcontrol-s0 speedcontrol 0 ACC
python3 GetResults.py ACC-error-s0 error 0 ACC
python3 GetResults.py ACC-hold-s0 hold 0 ACC
python3 GetResults.py ACC-override-s0 override 0 ACC
python3 GetResults.py ACC-off-s0 off 0 ACC
python3 GetResults.py ACC-standby-s1 standby 1 ACC
python3 GetResults.py ACC-following-s1 following 1 ACC
python3 GetResults.py ACC-speedcontrol-s1 speedcontrol 1 ACC
python3 GetResults.py ACC-error-s1 error 1 ACC
python3 GetResults.py ACC-hold-s1 hold 1 ACC
python3 GetResults.py ACC-override-s1 override 1 ACC
python3 GetResults.py ACC-off-s1 off 1 ACC
python3 GetResults.py ACC-standby-s2 standby 2 ACC
python3 GetResults.py ACC-following-s2 following 2 ACC
python3 GetResults.py ACC-speedcontrol-s2 speedcontrol 2 ACC
python3 GetResults.py ACC-error-s2 error 2 ACC
python3 GetResults.py ACC-hold-s2 hold 2 ACC
python3 GetResults.py ACC-override-s2 override 2 ACC
python3 GetResults.py ACC-off-s2 off 2 ACC
python3 GetResults.py ACC-standby-s3 standby 3 ACC
python3 GetResults.py ACC-following-s3 following 3 ACC
python3 GetResults.py ACC-speedcontrol-s3 speedcontrol 3 ACC
python3 GetResults.py ACC-error-s3 error 3 ACC
python3 GetResults.py ACC-hold-s3 hold 3 ACC
python3 GetResults.py ACC-override-s3 override 3 ACC
python3 GetResults.py ACC-off-s3 off 3 ACC
python3 GetResults.py ACC-standby-s4 standby 4 ACC
python3 GetResults.py ACC-following-s4 following 4 ACC
python3 GetResults.py ACC-speedcontrol-s4 speedcontrol 4 ACC
python3 GetResults.py ACC-error-s4 error 4 ACC
python3 GetResults.py ACC-hold-s4 hold 4 ACC
python3 GetResults.py ACC-override-s4 override 4 ACC
python3 GetResults.py ACC-off-s4 off 4 ACC
python3 GetResults.py ACC-standby-s5 standby 5 ACC
python3 GetResults.py ACC-following-s5 following 5 ACC
python3 GetResults.py ACC-speedcontrol-s5 speedcontrol 5 ACC
python3 GetResults.py ACC-error-s5 error 5 ACC
python3 GetResults.py ACC-hold-s5 hold 5 ACC
python3 GetResults.py ACC-override-s5 override 5 ACC
python3 GetResults.py ACC-off-s5 off 5 ACC
python3 GetResults.py ACC-standby-s6 standby 6 ACC
python3 GetResults.py ACC-following-s6 following 6 ACC
python3 GetResults.py ACC-speedcontrol-s6 speedcontrol 6 ACC
python3 GetResults.py ACC-error-s6 error 6 ACC
python3 GetResults.py ACC-hold-s6 hold 6 ACC
python3 GetResults.py ACC-override-s6 override 6 ACC
python3 GetResults.py ACC-off-s6 off 6 ACC
python3 GetResults.py ACC-standby-s7 standby 7 ACC
python3 GetResults.py ACC-following-s7 following 7 ACC
python3 GetResults.py ACC-speedcontrol-s7 speedcontrol 7 ACC
python3 GetResults.py ACC-error-s7 error 7 ACC
python3 GetResults.py ACC-hold-s7 hold 7 ACC
python3 GetResults.py ACC-override-s7 override 7 ACC
python3 GetResults.py ACC-off-s7 off 7 ACC
